### ISSUE TITLE
Chisel 3.2 Support for soDLA

### ISSUE THREAD

**Issue by redpanda3** [chipsalliance/chisel3#1255]
**Type of issue**:  feature request

**Impact**: no functional change

**Development Phase**: request

**Other information**

**If the current behavior is a bug, please provide the steps to reproduce the problem:** Not a bug.

**What is the current behavior?**

In the soDLA main branch, the version is chisel3.2. nv_large generator, when generating cmac module, will fail because of outOfMemory error. While in the beta branch, the default version is chisel3.1, there is no such problem.

**What is the expected behavior?**

nv_large successfully generated under chisel3.2

**Please tell us about your environment:**
 - version: `3.2.+`
 - OS: `Ubuntu x86_64`

**What is the use case for changing the behavior?**

nv_large generator.

**Comment by jackkoenig** [comment]
Can you provide details on how to reproduce (eg. repo to clone and command(s) to run).  In general, this kind of issue is fixed by simply increasing the amount of memory you give to java (`-mem` argument to `sbt` or `-Xmx` argument to `java`).

Can you try increasing the memory and let us know the difference in how much extra `3.2` is requiring? Modest increases are probably expected as the language develops, but if it's a large amount it's probably a bug somewhere.
